### ISSUE TITLE
Use default params

### ISSUE THREAD

**Issue by fagci** [CalfCrusher/WPHunter#1]
https://github.com/CalfCrusher/WPHunter/blob/0e68925a12e8d55dea468155dd853b9df6ff74e8/WPHunter.py#L28

`'\n'.strip('\n')` produces empty string. So, instead you can use just `print()`.

Note, that `print` function has some [interesting params](https://docs.python.org/3/library/functions.html#print) to use.

**Comment by CalfCrusher** [comment]
Thanks for suggestion, i'll commit those, code was written in less then 1 hour, today i'll check it better ;)
